#!/usr/bin/env node
/**
 * verify-deploy.mjs — Deploy Graph Integrity checks
 *
 * Generated by loom-cli v1.7.6 for project agentwatch-main.
 *
 * Runs three universal checks (stack-agnostic):
 *   1. Env polarity       — default .env must not reference a prod-tagged service
 *   2. Config consistency — Dockerfile migrate steps must not be bypassed by platform startCommand
 *   3. Out-of-band DDL    — ALTER/CREATE/DROP TABLE/INDEX in diff must live in migration files
 *
 * Exit codes:
 *   0 — PASS   (all checks passed or skipped-with-reason)
 *   1 — WARN   (one or more checks flagged non-fatal issues)
 *   2 — FAIL   (one or more checks found a blocker)
 *
 * Reads:
 *   .loom/stack.yml           (committed, identifies platforms/databases/orms)
 *   .loom/environments.yml    (committed, identifies dev/staging/prod environments)
 *   Dockerfile, railway.json, fly.toml, vercel.json, render.yaml (platform configs)
 *   .env, .env.local          (credential identity)
 *   git diff <base>...HEAD    (scanning for out-of-band DDL)
 *
 * Exits 0 PASS if no loom manifests present — the script degrades gracefully on non-loom projects.
 * Stack-specific check modules (Prisma, Drizzle, Railway, Supabase) live under `scripts/checks/`
 * and are dispatched after the universal checks based on `.loom/stack.yml`.
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { parse as yamlParse } from "yaml";

const REPO_ROOT = process.cwd();
const RESET = "\x1b[0m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const DIM = "\x1b[2m";

// ── Results aggregation ────────────────────────────────────────────────────

/** @type {Array<{ check: string, status: "PASS"|"WARN"|"FAIL"|"SKIP", message: string }>} */
const results = [];

function record(check, status, message) {
  results.push({ check, status, message });
}

// ── Safe I/O helpers ───────────────────────────────────────────────────────

function safeRead(rel) {
  try {
    return fs.readFileSync(path.join(REPO_ROOT, rel), "utf-8");
  } catch {
    return null;
  }
}

function safeYaml(rel) {
  const raw = safeRead(rel);
  if (!raw) return null;
  try {
    const parsed = yamlParse(raw);
    if (!parsed || typeof parsed !== "object") return null;
    return parsed;
  } catch {
    return null;
  }
}

function fileExists(rel) {
  try {
    return fs.existsSync(path.join(REPO_ROOT, rel));
  } catch {
    return false;
  }
}

// ── Check 1: env polarity ─────────────────────────────────────────────────
//
// The default .env (used by developers and local scripts) must not reference
// a service that is tagged as production in .loom/environments.yml. This is
// the "Virtus-class" reversal: .env points at prod, any local script is
// running against production.

async function checkEnvPolarity() {
  const envManifest = safeYaml(".loom/environments.yml");
  if (!envManifest) {
    record(
      "env-polarity",
      "WARN",
      ".loom/environments.yml missing or unparseable — cannot verify polarity. Run `loom --rescan-tooling`."
    );
    return;
  }

  const envs = (envManifest && envManifest.environments) || {};
  let defaultName = null;
  let defaultEnv = null;
  for (const [name, env] of Object.entries(envs)) {
    if (env && env.is_default === true) {
      defaultName = name;
      defaultEnv = env;
      break;
    }
  }
  if (!defaultEnv) {
    record(
      "env-polarity",
      "WARN",
      "No default environment declared in .loom/environments.yml."
    );
    return;
  }

  // Fatal: the default env itself is marked production. Polarity inverted at
  // the manifest level.
  if (defaultEnv.is_production === true) {
    record(
      "env-polarity",
      "FAIL",
      `Default environment "${defaultName}" is marked is_production: true. Flip is_default to a non-prod environment.`
    );
    return;
  }

  // Read .env or .env.local. If neither exists, skip gracefully.
  const envFileContent = safeRead(".env") || safeRead(".env.local");
  if (!envFileContent) {
    record("env-polarity", "SKIP", "No .env or .env.local to check.");
    return;
  }

  // Collect identifying strings from every prod-tagged service: URLs,
  // project IDs, hosts, anything that could uniquely identify a prod
  // resource. Skip very short values (booleans, single-word tags).
  const prodIdentifiers = [];
  for (const [envName, env] of Object.entries(envs)) {
    if (!env || env.is_production !== true) continue;
    const services = env.services || {};
    for (const [svcName, svc] of Object.entries(services)) {
      if (!svc || typeof svc !== "object") continue;
      for (const [key, value] of Object.entries(svc)) {
        if (typeof value !== "string") continue;
        if (value.length <= 8) continue;
        prodIdentifiers.push({ envName, svcName, key, value });
      }
    }
  }

  if (prodIdentifiers.length === 0) {
    record(
      "env-polarity",
      "WARN",
      "No prod service identifiers declared in .loom/environments.yml. " +
        "Populate `environments.<prodEnv>.services` (e.g. supabase.url, " +
        "supabase.project_id, railway.project_id) before relying on this check. " +
        "Until populated, env polarity cannot be verified."
    );
    return;
  }

  const matches = [];
  for (const ident of prodIdentifiers) {
    if (envFileContent.includes(ident.value)) {
      matches.push(ident);
    }
  }

  if (matches.length > 0) {
    const detail = matches
      .map((m) => `${m.envName}.${m.svcName}.${m.key}`)
      .join(", ");
    record(
      "env-polarity",
      "FAIL",
      `Default .env references prod-tagged service(s): ${detail}. Env polarity reversed — this is the Virtus-class failure mode. Flip .env to dev creds.`
    );
    return;
  }

  record(
    "env-polarity",
    "PASS",
    "Default .env does not reference any prod-tagged service."
  );
}

// ── Check 2: config consistency ────────────────────────────────────────────
//
// If a Dockerfile runs migrate/seed/schema commands as part of its
// CMD/ENTRYPOINT, a platform-level startCommand that doesn't include those
// commands silently bypasses them. This is a Virtus-class silent override.

const MIGRATE_KEYWORDS = ["migrate", "db:push", "schema:sync", "seed"];

function containsMigrateKeyword(haystack) {
  if (!haystack) return false;
  const lower = haystack.toLowerCase();
  return MIGRATE_KEYWORDS.some((kw) => lower.includes(kw));
}

async function checkConfigConsistency() {
  const stack = safeYaml(".loom/stack.yml");
  if (!stack) {
    record("config-consistency", "WARN", ".loom/stack.yml missing.");
    return;
  }

  const platforms = (stack && stack.platforms) || [];
  const dockerPlatform = platforms.find(
    (p) => p && (p.name === "docker" || p.name === "docker-compose")
  );
  if (!dockerPlatform) {
    record("config-consistency", "SKIP", "No Dockerfile detected.");
    return;
  }
  const dockerfilePath =
    (dockerPlatform.metadata && dockerPlatform.metadata.dockerfile_path) ||
    "Dockerfile";
  const dockerContent = safeRead(dockerfilePath);
  if (!dockerContent) {
    record(
      "config-consistency",
      "SKIP",
      `Dockerfile at ${dockerfilePath} not readable.`
    );
    return;
  }

  if (!containsMigrateKeyword(dockerContent)) {
    record(
      "config-consistency",
      "SKIP",
      "Dockerfile does not mention migrate/seed/schema. No override check needed."
    );
    return;
  }

  const overrides = [];

  for (const platform of platforms) {
    if (!platform) continue;
    if (platform.name === "docker" || platform.name === "docker-compose") continue;

    if (platform.name === "railway") {
      const startCmd = readRailwayStartCommand();
      if (startCmd !== null && !containsMigrateKeyword(startCmd)) {
        overrides.push({
          platform: "railway",
          file: "railway.json",
          startCommand: startCmd,
        });
      }
    } else if (platform.name === "fly") {
      const flyCmds = readFlyCommands();
      // Fly allows both `release_command` (runs before deploy) and processes.
      // If release_command is absent AND no process includes migrate, it's an
      // override relative to the Dockerfile CMD.
      if (flyCmds) {
        const hasMigrateRelease = containsMigrateKeyword(flyCmds.release);
        const hasMigrateProcess = (flyCmds.processes || []).some((p) =>
          containsMigrateKeyword(p)
        );
        if (
          !hasMigrateRelease &&
          !hasMigrateProcess &&
          (flyCmds.release || (flyCmds.processes || []).length > 0)
        ) {
          overrides.push({
            platform: "fly",
            file: "fly.toml",
            startCommand:
              flyCmds.release ||
              (flyCmds.processes || []).join(" | ") ||
              "(processes)",
          });
        }
      }
    } else if (platform.name === "vercel") {
      const buildCmd = readVercelBuildCommand();
      if (buildCmd !== null && !containsMigrateKeyword(buildCmd)) {
        overrides.push({
          platform: "vercel",
          file: "vercel.json",
          startCommand: buildCmd,
        });
      }
    } else if (platform.name === "render") {
      const renderCmds = readRenderStartCommands();
      for (const rc of renderCmds) {
        if (!containsMigrateKeyword(rc.startCommand)) {
          overrides.push({
            platform: "render",
            file: "render.yaml",
            startCommand: `${rc.name}: ${rc.startCommand}`,
          });
        }
      }
    }
  }

  if (overrides.length > 0) {
    const detail = overrides
      .map((o) => `${o.platform} (${o.file}: "${o.startCommand}")`)
      .join(", ");
    record(
      "config-consistency",
      "FAIL",
      `Dockerfile runs migrate but platform config overrides with a startCommand that bypasses it: ${detail}. This is the Virtus-class silent config override.`
    );
    return;
  }

  record(
    "config-consistency",
    "PASS",
    "Dockerfile migrate step is not overridden by platform config."
  );
}

function readRailwayStartCommand() {
  const raw = safeRead("railway.json");
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    const startCmd =
      (parsed && parsed.deploy && parsed.deploy.startCommand) ||
      (parsed && parsed.startCommand) ||
      null;
    if (typeof startCmd !== "string" || startCmd.length === 0) return null;
    return startCmd;
  } catch {
    return null;
  }
}

function readFlyCommands() {
  const raw = safeRead("fly.toml");
  if (!raw) return null;
  // Minimal TOML-ish parse for the two fields we care about. We intentionally
  // avoid pulling a full TOML parser — these fields are simple keys.
  const release = extractTomlString(raw, "release_command");
  const processes = [];
  // [processes] section: each `key = "value"` line following the header.
  const procMatch = raw.match(/\[processes\]([\s\S]*?)(?=\n\[|$)/);
  if (procMatch) {
    const block = procMatch[1];
    const lineRe = /^\s*(\w+)\s*=\s*"([^"]*)"/gm;
    let m;
    while ((m = lineRe.exec(block)) !== null) {
      processes.push(m[2]);
    }
  }
  return { release, processes };
}

function extractTomlString(raw, key) {
  const re = new RegExp(`^\\s*${key}\\s*=\\s*"([^"]*)"`, "m");
  const m = raw.match(re);
  return m ? m[1] : null;
}

function readVercelBuildCommand() {
  const raw = safeRead("vercel.json");
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    const cmd =
      (parsed && parsed.buildCommand) ||
      (parsed && parsed.build && parsed.build.command) ||
      null;
    if (typeof cmd !== "string" || cmd.length === 0) return null;
    return cmd;
  } catch {
    return null;
  }
}

function readRenderStartCommands() {
  const raw = safeRead("render.yaml");
  if (!raw) return [];
  const parsed = (() => {
    try {
      return yamlParse(raw);
    } catch {
      return null;
    }
  })();
  if (!parsed || typeof parsed !== "object") return [];
  const services = Array.isArray(parsed.services) ? parsed.services : [];
  const out = [];
  for (const svc of services) {
    if (!svc || typeof svc !== "object") continue;
    const startCommand =
      typeof svc.startCommand === "string" ? svc.startCommand : null;
    if (!startCommand) continue;
    out.push({ name: svc.name || "service", startCommand });
  }
  return out;
}

// ── Check 3: out-of-band DDL ───────────────────────────────────────────────
//
// DDL (ALTER TABLE, CREATE TABLE, DROP TABLE, CREATE/DROP INDEX) in the diff
// must live inside the ORM's migrations directory. Schema changes applied
// via SQL editor or ad-hoc scripts drift the deploy graph silently.

const DDL_REGEX =
  /\b(ALTER\s+TABLE|CREATE\s+TABLE|DROP\s+TABLE|CREATE\s+INDEX|DROP\s+INDEX|CREATE\s+UNIQUE\s+INDEX)\b/gi;

async function checkOutOfBandDDL() {
  const stack = safeYaml(".loom/stack.yml");

  // Determine base branch. Prefer main, fall back to master. If neither
  // exists (new repo, detached HEAD), skip with reason.
  let baseBranch = null;
  try {
    execSync("git rev-parse --verify main", {
      cwd: REPO_ROOT,
      stdio: "pipe",
    });
    baseBranch = "main";
  } catch {
    try {
      execSync("git rev-parse --verify master", {
        cwd: REPO_ROOT,
        stdio: "pipe",
      });
      baseBranch = "master";
    } catch {
      record("out-of-band-ddl", "SKIP", "No main or master branch found.");
      return;
    }
  }

  // A test-only hook for deterministic diffs — integration tests set this
  // to the path of a file containing a pre-canned diff output. Production
  // invocations never set it. Absolute paths resolve verbatim; relative
  // paths are interpreted against REPO_ROOT.
  const overridePath = process.env.LOOM_VERIFY_DEPLOY_DIFF_FILE;
  let diffOutput;
  if (overridePath) {
    const resolved = path.isAbsolute(overridePath)
      ? overridePath
      : path.join(REPO_ROOT, overridePath);
    try {
      diffOutput = fs.readFileSync(resolved, "utf-8");
    } catch {
      diffOutput = "";
    }
  } else {
    try {
      diffOutput = execSync(`git diff ${baseBranch}...HEAD --unified=0`, {
        cwd: REPO_ROOT,
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
      record(
        "out-of-band-ddl",
        "SKIP",
        `Could not run git diff against ${baseBranch}.`
      );
      return;
    }
  }

  if (!diffOutput || !diffOutput.trim()) {
    record("out-of-band-ddl", "SKIP", "No diff to scan.");
    return;
  }

  const migrationsDir =
    (stack &&
      Array.isArray(stack.orms) &&
      stack.orms[0] &&
      stack.orms[0].metadata &&
      stack.orms[0].metadata.migrations_dir) ||
    null;

  const fileChunks = parseDiffIntoFiles(diffOutput);

  const outOfBand = [];
  for (const chunk of fileChunks) {
    const matches = chunk.content.match(DDL_REGEX);
    if (!matches || matches.length === 0) continue;
    const isMigration =
      migrationsDir && chunk.filePath.startsWith(migrationsDir);
    if (isMigration) continue;
    const normalized = Array.from(
      new Set(matches.map((s) => s.replace(/\s+/g, " ").toUpperCase()))
    );
    outOfBand.push({ file: chunk.filePath, ddl: normalized });
  }

  if (outOfBand.length > 0) {
    const detail = outOfBand
      .map((m) => `${m.file} (${m.ddl.join(", ")})`)
      .join(", ");
    record(
      "out-of-band-ddl",
      "FAIL",
      `DDL found outside migrations directory: ${detail}. Every schema change must have a committed migration file.`
    );
    return;
  }

  record(
    "out-of-band-ddl",
    "PASS",
    "No out-of-band DDL detected in diff."
  );
}

/**
 * Parse a unified-diff output into per-file chunks containing only the added
 * lines ("+" prefixed, minus the leading "+"). File path is taken from the
 * `+++ b/<path>` header — or, for new/deleted files, from the `diff --git`
 * header. Never throws.
 */
function parseDiffIntoFiles(diff) {
  const chunks = [];
  const lines = diff.split("\n");
  let currentPath = null;
  let currentAdded = [];

  const flush = () => {
    if (currentPath !== null) {
      chunks.push({ filePath: currentPath, content: currentAdded.join("\n") });
    }
    currentPath = null;
    currentAdded = [];
  };

  for (const line of lines) {
    if (line.startsWith("diff --git ")) {
      flush();
      // diff --git a/<path> b/<path>
      const m = line.match(/^diff --git a\/(.+?) b\/(.+)$/);
      if (m) {
        currentPath = m[2];
      }
      continue;
    }
    if (line.startsWith("+++ ")) {
      // +++ b/<path>  (trumps the diff --git path if present)
      const m = line.match(/^\+\+\+ b\/(.+)$/);
      if (m) {
        currentPath = m[1];
      }
      continue;
    }
    // Skip diff metadata lines.
    if (
      line.startsWith("index ") ||
      line.startsWith("--- ") ||
      line.startsWith("@@ ") ||
      line.startsWith("new file mode") ||
      line.startsWith("deleted file mode") ||
      line.startsWith("similarity index") ||
      line.startsWith("rename from") ||
      line.startsWith("rename to")
    ) {
      continue;
    }
    // Accumulate added-line content.
    if (line.startsWith("+") && !line.startsWith("+++")) {
      currentAdded.push(line.slice(1));
    }
  }
  flush();

  return chunks;
}

// ── Stack-specific check dispatcher ────────────────────────────────────────
//
// After the three universal checks, discover which stack-specific check
// modules are available in the user's repo and invoke each. A module lives
// at `scripts/checks/<name>.mjs` and must export `runChecks(context)`.
//
// Absent modules are a no-op (user may have declined scaffolding). Errors
// thrown by a module are caught and recorded as WARN — dispatcher never
// crashes the whole run.

async function runStackSpecificChecks() {
  const stack = safeYaml(".loom/stack.yml");
  if (!stack) return; // already warned in main()

  const allElements = [
    ...((stack.platforms || []).map((p) => ({ name: p.name, category: "platforms" }))),
    ...((stack.databases || []).map((d) => ({ name: d.name, category: "databases" }))),
    ...((stack.orms || []).map((o) => ({ name: o.name, category: "orms" }))),
  ];

  const environments = safeYaml(".loom/environments.yml");

  for (const elem of allElements) {
    const checkPath = path.join(REPO_ROOT, "scripts", "checks", `${elem.name}.mjs`);
    if (!fs.existsSync(checkPath)) continue; // not scaffolded, no-op

    try {
      const mod = await import(checkPath);
      if (typeof mod.runChecks !== "function") {
        record(
          elem.name,
          "WARN",
          `Check module ${elem.name}.mjs exists but exports no runChecks function — ignoring.`
        );
        continue;
      }
      await mod.runChecks({
        repoRoot: REPO_ROOT,
        stack,
        environments,
        helpers: { safeRead, safeYaml, fileExists, record },
      });
    } catch (err) {
      record(
        elem.name,
        "WARN",
        `Check module ${elem.name}.mjs threw during load or run: ${err?.message ?? String(err)}. Skipping.`
      );
    }
  }
}

// ── Main ───────────────────────────────────────────────────────────────────

function statusColor(status) {
  if (status === "PASS") return GREEN;
  if (status === "WARN") return YELLOW;
  if (status === "FAIL") return RED;
  return DIM;
}

async function main() {
  if (!fileExists(".loom/stack.yml")) {
    process.stdout.write(
      `${DIM}No .loom/stack.yml found — skipping all checks. Run \`loom\` to scaffold.${RESET}\n`
    );
    process.exit(0);
  }

  await checkEnvPolarity();
  await checkConfigConsistency();
  await checkOutOfBandDDL();
  await runStackSpecificChecks();

  const failed = results.filter((r) => r.status === "FAIL");
  const warned = results.filter((r) => r.status === "WARN");
  const passed = results.filter((r) => r.status === "PASS");
  const skipped = results.filter((r) => r.status === "SKIP");

  for (const r of results) {
    const color = statusColor(r.status);
    process.stdout.write(
      `${color}[${r.status}]${RESET} ${r.check}: ${r.message}\n`
    );
  }
  process.stdout.write(
    `\nSummary: ${passed.length} pass, ${warned.length} warn, ${failed.length} fail, ${skipped.length} skip\n`
  );

  if (failed.length > 0) process.exit(2);
  if (warned.length > 0) process.exit(1);
  process.exit(0);
}

main().catch((err) => {
  process.stderr.write(`${RED}verify-deploy crashed: ${err.message}${RESET}\n`);
  process.exit(2);
});
